apiVersion: v1
data:
  install-config: |
    apiVersion: v1
    baseDomain: communityus.net
    compute:
    - architecture: amd64
      hyperthreading: Enabled
      name: worker
      platform: {}
      replicas: 3
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      platform:
        azure:
          osDisk:
            diskSizeGB: 1024
          type: Standard_D8s_v3
          zones:
          - "1"
          - "3"
          - "2"
      replicas: 3
    metadata:
      creationTimestamp: null
      name: ocp4
    networking:
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.0.0.0/16
      networkType: OpenShiftSDN
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      azure:
        baseDomainResourceGroupName: playpassmedia104
        region: westus2
    publish: External
    pullSecret: ""
    sshKey: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGBcxrGWdbSGc+QEv0kfnAeYoEd9Euwp/3q+iVTC+Hyt desktop@steamos
kind: ConfigMap
metadata:
  name: cluster-config-v1
  namespace: kube-system
