apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  namespace: openshift-cluster-version
  name: version
spec:
  upstream: https://api.openshift.com/api/upgrades_info/v1/graph
  channel: stable-4.4
  clusterID: 6f5d115c-d455-41fc-a369-3a8caa9834e7
